import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        "surface-section": "var(--color-surface-section)",
        surface: "var(--color-surface)",
        "surface-elevated": "var(--color-surface-elevated)",
        "surface-chrome": "var(--color-surface-chrome)",
        "surface-chrome-strong": "var(--color-surface-chrome-strong)",
        "surface-inner": "var(--color-surface-inner)",
        "surface-active": "var(--color-surface-active)",
        "surface-highlight": "var(--color-surface-highlight)",
        "surface-header": "var(--color-surface-header)",
        border: "var(--color-border)",
        "border-strong": "var(--color-border-strong)",
        "border-nested": "var(--color-border-nested)",
        "border-interactive": "var(--color-border-interactive)",
        "border-active": "var(--color-border-active)",
        foreground: "var(--color-foreground)",
        "foreground-secondary": "var(--color-foreground-secondary)",
        "card-title": "var(--color-card-title)",
        "text-normal": "var(--color-text-normal)",
        "text-subtle": "var(--color-text-subtle)",
        muted: "var(--color-muted)",
        financial: "var(--color-financial)",
        profit: "var(--color-profit)",
        "profit-bg": "var(--color-profit-bg)",
        "profit-border": "var(--color-profit-border)",
        loss: "var(--color-loss)",
        "loss-bg": "var(--color-loss-bg)",
        "loss-border": "var(--color-loss-border)",
        warning: "var(--color-warning)",
        "warning-bg": "var(--color-warning-bg)",
        "warning-border": "var(--color-warning-border)",
        info: "var(--color-info)",
        "info-bg": "var(--color-info-bg)",
        "info-border": "var(--color-info-border)",
        accent: "var(--color-accent)",
        primary: "var(--color-primary)",
        "primary-hover": "var(--color-primary-hover)",
        "primary-soft": "var(--color-primary-soft)",
        "primary-foreground": "var(--color-primary-foreground)",
        overlay: "var(--color-overlay)",
        "table-header": "var(--color-table-header)",
        "table-header-text": "var(--color-table-header-text)",
        "table-row": "var(--color-table-row)",
        "table-row-alt": "var(--color-table-row-alt)",
        "table-hover": "var(--color-table-hover)",
        "table-border": "var(--color-table-border)",
        "switcher-bg": "var(--color-switcher-bg)",
        "switcher-border": "var(--color-switcher-border)",
        "nav-inactive": "var(--color-nav-inactive)",
        "nav-active-bg": "var(--color-nav-active-bg)",
        "modal-header": "var(--color-modal-header)",
        "input-border": "var(--color-input-border)",
        "input-placeholder": "var(--color-input-placeholder)",
        focus: "var(--color-focus)",
        "secondary-btn": "var(--color-secondary-btn)",
        "secondary-btn-hover": "var(--color-secondary-btn-hover)",
        "chart-plot": "var(--color-chart-plot)",
        "surface-inner-hover": "var(--color-surface-inner-hover)",
        "surface-inner-hover-soft": "var(--color-surface-inner-hover-soft)",
        "border-hover": "var(--color-border-hover)",
      },
      boxShadow: {
        card: "0 1px 2px var(--color-shadow-card)",
        chrome: "0 -1px 4px var(--color-shadow-chrome)",
        modal: "0 8px 32px var(--color-shadow-modal)",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
      },
    },
  },
  plugins: [],
};

export default config;
